// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKd0Ip6la_wxrszfZO1zd1kjrl0o1TGnY',
    appId: '1:815039019028:web:2dc89b63f5d650da290f01',
    messagingSenderId: '815039019028',
    projectId: 'burpeebata-dev',
    authDomain: 'burpeebata-dev.firebaseapp.com',
    storageBucket: 'burpeebata-dev.firebasestorage.app',
    measurementId: 'G-S3S05WNG57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUwmWkfrCPqCY3GkdoQisLYytIPULmTgE',
    appId: '1:815039019028:android:f8256fbc4226e534290f01',
    messagingSenderId: '815039019028',
    projectId: 'burpeebata-dev',
    storageBucket: 'burpeebata-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSlogI6eJ8WL994zzo0yqtuGCvZo_bcBo',
    appId: '1:815039019028:ios:78a3b77cfcee964e290f01',
    messagingSenderId: '815039019028',
    projectId: 'burpeebata-dev',
    storageBucket: 'burpeebata-dev.firebasestorage.app',
    iosBundleId: 'com.burpeebata.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSlogI6eJ8WL994zzo0yqtuGCvZo_bcBo',
    appId: '1:815039019028:ios:78a3b77cfcee964e290f01',
    messagingSenderId: '815039019028',
    projectId: 'burpeebata-dev',
    storageBucket: 'burpeebata-dev.firebasestorage.app',
    iosBundleId: 'com.burpeebata.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKd0Ip6la_wxrszfZO1zd1kjrl0o1TGnY',
    appId: '1:815039019028:web:1ef7f4136db991e5290f01',
    messagingSenderId: '815039019028',
    projectId: 'burpeebata-dev',
    authDomain: 'burpeebata-dev.firebaseapp.com',
    storageBucket: 'burpeebata-dev.firebasestorage.app',
    measurementId: 'G-DTX92D1B0C',
  );

}